# Generated by Django 4.1.7 on 2023-03-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус заявки', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_seria', models.CharField(help_text='Серия паспорта клиента', max_length=2)),
                ('pasport_id', models.IntegerField(help_text='Номер паспорта клиента')),
                ('country', django_countries.fields.CountryField(help_text='Страна проживания клиента', max_length=2)),
                ('city', models.CharField(help_text='Город проживания клиента', max_length=50)),
                ('street', models.CharField(help_text='Улица проживания клиента', max_length=50)),
                ('house_number', models.CharField(help_text='Номер дома клиента', max_length=50)),
                ('apartnent_number', models.CharField(help_text='Номер квартиры клиента', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(help_text='Сумма кредита')),
                ('currency', models.CharField(help_text='Валюта', max_length=1)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заявки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status')),
            ],
        ),
    ]
