# Generated by Django 4.1.7 on 2023-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pasport_id',
            field=models.IntegerField(blank=True, help_text='Номер паспорта клиента', null=True),
        ),
    ]
