# Generated by Django 4.1.7 on 2023-03-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_pasport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(help_text='Владелец заявки', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.userprofile'),
        ),
    ]
